include_directories(${CMAKE_CURRENT_LIST_DIR})

include(${CMAKE_CURRENT_LIST_DIR}/../FormatWidgets/allformatwidgets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../XArchive/xarchives.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../XShortcuts/xshortcuts.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../Controls/xmodel_archiverecords.cmake)

set(ARCHIVE_WIDGET_SOURCES
    ${ALLFORMATWIDGETS_SOURCES}
    ${XARCHIVES_SOURCES}
    ${XSHORTCUTS_SOURCES}
    ${XMODEL_ARCHIVERECORDS_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/archive_widget.cmake
    ${CMAKE_CURRENT_LIST_DIR}/archive_widget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/archive_widget.ui
    ${CMAKE_CURRENT_LIST_DIR}/createviewmodelprocess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogarchive.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogcreateviewmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogshowimage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogshowimage.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogunpackfile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unpackfileprocess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarchivewidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarchivewidget.ui
    ${CMAKE_CURRENT_LIST_DIR}/xgenericarchivewidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgenericarchivewidget.ui
    ${CMAKE_CURRENT_LIST_DIR}/archiveexplorerwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/archiveexplorerwidget.ui
    )
