include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XMODEL_ARCHIVERECORDS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Controls/xmodel_archiverecords.cmake)
    set(ARCHIVEEXPLORERWIDGET_SOURCES ${ARCHIVEEXPLORERWIDGET_SOURCES} ${XMODEL_ARCHIVERECORDS_SOURCES})
endif()

if (NOT DEFINED XTABLEVIEW_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Controls/xtableview.cmake)
    set(ARCHIVEEXPLORERWIDGET_SOURCES ${ARCHIVEEXPLORERWIDGET_SOURCES} ${XTABLEVIEW_SOURCES})
endif()

if (NOT DEFINED XARCHIVES_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XArchive/xarchives.cmake)
    set(ARCHIVEEXPLORERWIDGET_SOURCES ${ARCHIVEEXPLORERWIDGET_SOURCES} ${XARCHIVES_SOURCES})
endif()

if (NOT DEFINED XSHORTCUTS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XShortcuts/xshortcuts.cmake)
    set(ARCHIVEEXPLORERWIDGET_SOURCES ${ARCHIVEEXPLORERWIDGET_SOURCES} ${XSHORTCUTS_SOURCES})
endif()

set(ARCHIVEEXPLORERWIDGET_SOURCES
    ${ARCHIVEEXPLORERWIDGET_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/archiveexplorerwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/archiveexplorerwidget.h
    ${CMAKE_CURRENT_LIST_DIR}/archiveexplorerwidget.ui
    )
